version: '3'

services:
  llm-app:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./source_data:/app/source_data
      - ./vectorestore:/app/vectorestore
      - ./model:/app/model
    environment:
      - UVICORN_HOST=127.0.0.1
      - UVICORN_PORT=7860
      - VECTOR_STORE=./vectorestore
      - SOURCE_DATA=./source_data
      - MODEL_PATH=./model/mistral-7b-instruct-v0.1.Q2_K.gguf
      - EMBED_MODEL=BAAI/bge-base-en-v1.5
      - TOGETHER_MODEL_PATH=mistralai/Mistral-7B-Instruct-v0.2